language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: PC1Dw5j7PYdjUJIl7Xs5dJWlz/nWJTJarAvBp/fqdXuBTQ1XMmQd2x/cRArW9FymINT7hlgG+PCjfbxQwo/sKhOxC2cZaoBh45w4ugZ9lYBZJyxD7kucKTgVPEFiRWPLFWqggQN4Qmu+M56lEMne2LSfMHUPEBFxa+l4TMGTagcy+hw++pO45v/0jeThyDsrmIL0y9ltGKuu0sxaPS/bOx5xG2Poi08ToWj1YQonKACw17eKDx35pvoyUBuWbdnioiIC3dxDHN6y3RHJeBjRZxPFy4Fzbkyj0fQVtGnD4BGpvr1ZN+KXJfUZRi1DpGarpklCHZjMugdRfD1d5GEDEjnIA2EHOmdmYyupiCaqjbViOgPDHbcpvnrcDA5jFpwJe/sRLSF0h1ocKvNytMOzAtFcpjfkTQ4BixAp4WcAFiQ6Yr1LZxmP3lhV1/xq1VtMw03ZK6X+7ERT3Oc6UR6nkVarim/j0E1gAF2iv0ZGgwbUGJdOSX/B0yYbbZ5oBcN3/opesgRAN4bxTP/ZWV46dW6Shg4hgEyzjCyeHVEuSjPIy7Ur0Ol7P4fKI8ONagmkYuf7Bd2Q6ZeEJg/OCV567c0b5sFeq91VQKDzxeSNm4/wjZFIW23IPAyQaPAa64Ph90cZFGTkCcX/823ksFo9U1s+7qfxAuMh738d15hT+G4=
