language: node_js
notifications:
  email: false
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: 'npm run greenkeeper:upload-lockfile'
after_success: npm run coverage:report
env:
  global:
    - FORCE_COLOR=1
    - NPM_CONFIG_COLOR=always
    - GK_LOCK_COMMIT_AMEND=true
