language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: hFApFzPf6s5HaQYvHymf0Pi7ep1XEYLrAWSPmwUYJhr8ZYdBl+NuACFbjJkdbj9S97fYQFfgFaxCg5T2jvvL1huXx5rzYaDYZmaICQV9Zp8uWihSnzWStbt7DAOQKa5v5X6MmvWTYcLElM86JsjK0Mus6atl9JZXa67YHhYBjJtdn5TCAH6Zx5GJURIl+qk+tT3mgHDoviyaUx4lw6v2EcMkeBnZh8KGa+LyjAaiNiZK7MXXBx8k4uBzuZibiohlFmGwOGMxltK7hzEpZEkeBQeh5pyRcWf+dmwF//jqF638PkOoBym7g580a73Vt05Yxh9TI2XbswCy4DYjf9IT2k1KPdGjLSDqKlIHEdffWghD6lelZQAGRxHr+FfCQIVeyJbOU+QzgDZEx/WHAqHf4GAQag8Ke/8F/xlGlQbln2h0PwVOnL1MHETv6HifFhI3I5QiQGLerAJeh15wGdyvCBsrkul4U0wmkh+Ojvou9IIpv9VHx4tb87FvIPXqWRrjlwPQhFYJB+QV1+12x14ekdSAZ7SNSoEsDQpecJ54SOipnL/vHZGXnafLwHUSmN+uBAzVqxVIMzb7z/h5+Y3eJkIW/EDX7JsZUhwxR7DcyYuYx64HBOmztpQ6adwSdKqCF3n4YLRIkriwlfHWeAK4ztETKK+C6Ba+s1u8Dwlg2Gs=
