language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: Ii2fGSc0Rh/UZPpxFd4z4EPgnvGdpRDU240gxMlEcaem7qk8lRLtjYRnluWDnffq2xfnYH5ozGjhYfKMML4qXxwSKfFncuZXGGSmP29RYZn46lQffvNa8F+OY0jW5oj0HBfYVvf4VUnDmZUKMmEL8uPkLsSweVoPjZ1Z3Ye1wiWVp6FbqJTHihLBuFBlH8Z+DnISyW5+9rIX48hoENzbnOUQD4adCJfRrQUsY/qJzmEsIhT9DJLCoGd8QzmW855Qb7AYUa2mHJaAm0CqCbdnp/qzDdVjfsUooc/soyhYUx0wIoF2JNUmTh7rQy7c2t90zt94oheaBUfkZ+KXgARE/EgQbd1zaVsTMF5Yf3ahHKaIPfD3um2cfxEcaWV/8O2L6KSf0Lp81iAb58jHkOy/JJb4w3lZK/Sn4zEVS0pOL+A/o9LCq9dwtPtSjQkwCfED316F7hFvcyRddFn6E0uQVH8TW7ASIhy1jbdX33QaknmKLdM701dy5DDL1c+8b5oFe58rxpRxGuGd7m7/z2mfQOh/b6XBETjYyI9spUzKkVYOoYnE+pQpXSKNVrB02R5nH8FAsOY5I8+nK2VXlIeRmru1MYVSetj7/mGT3GIxnmhwavUqCyil0GZ2oHT8lHavdcRlOe2J2LbGQ4i+tLhVLBGyrjosbt11BfzUJ2D35j0=
  - secure: SNkLeJjagtT4BeRuj/yAPfTMcnxrn9B/a2sXjVWfwvM18gEHGCJSsvovikfa9517aytkN6/08YzA7DM0CkzM0k9TlosIohldgDCY5X0OWKF+SeD5XLoO9YHsI6ZF8hEFhZP0JeYKB7fe/MWs2GhdmzeVe7zCiGcr0NrPo211uER1H6oBl9a2D9mGPgWGmQ3yU/CbNwL513/4KkIX11M+T3bMb17i8h9ihi9FIq0ue7tWZncMVdwNQQGcbf1quaTDtLkJ5LfZ8OGsSGFdbtu42e0Ta92OCxnOpKOuILwte/1GdVTy/+Ll+mOuLx7yRArIJrL7jECaD0IR6IZJqOElt1PHL847puB6ds3+GBaXAkhdkTAjuU0DMv4W+D/MH17iTyIQwsTVFe0kBlVrkI1XN5qeqtOBPf83iA2ntvbBB3BzOoC/WjpLijmjGJUsNYcWB98kGMco7ZC2iQikc1gedx7Zboe0py/9mtOYvZ5GI22Z5FXDDCpU+wFbVhJDrT3zbN+AuIicdKFvcHprSxij9Aog5R+hSY1Zo/nJrUEIZ8ru8Ka72Zf/WA2a7Q62KPpKfyDNR3wGgxFY25he0YQgadIDSuy/M49G0/QfZ6ymjTRTGl2VlWbAzO6FCb619FHv2KNHCacWGzZa0RXO7t4LXWGwPqvSuyb1ODGV44BCqLU=
